modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
issueTrackerURL=""

[[mods]]
modId="reignofnether"
version="1.0.2"
displayName="Reign of Nether Overhaul"
logoFile="examplemod.png"
credits="Thanks to Technovision for his YouTube guides"
authors="SoLegendary, Goodbird, Codex"
description='''
Minecraft, except it's an RTS (Overhaul Version 1.0.2)
'''

[[dependencies.reignofnether]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.reignofnether]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[mods]]
modId="ron_golem_healer_integration"
version="1.0.2"
displayName="RoN Golem Healer Integration"
authors="Codex"
description='''Integrates the original Villager Golem Healer entity as a Reign of Nether unit.'''

[[dependencies.ron_golem_healer_integration]]
modId="forge"
mandatory=true
versionRange="[47.4.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.ron_golem_healer_integration]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.ron_golem_healer_integration]]
modId="reignofnether"
mandatory=true
versionRange="[1.0.2,)"
ordering="AFTER"
side="BOTH"

[[dependencies.ron_golem_healer_integration]]
modId="villagergolemhealer"
mandatory=true
versionRange="[1.0.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.ron_golem_healer_integration]]
modId="guardillagers"
mandatory=true
versionRange="[1.0.1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.ron_golem_healer_integration]]
modId="slash_illager"
mandatory=true
versionRange="[1.0.0,)"
ordering="AFTER"
side="BOTH"
